### ISSUE TITLE
Bug - syntax error on retry connection

### ISSUE THREAD

**Issue by lasergoat** [jeremydaly/serverless-mysql#64]
I am purposefully testing what happens when connecting to a database which requires a VPN. The Serverless-mysql produces a syntax error in this case.

I am running with `sls invoke local --function app` and my connection code looks like this:

```// handler.ts for serverless
import { config } from "dotenv";
config();

import partnerSync from "./partnerSync";

import { Connection, ConnectionConfig } from "mysql";

const connectionConfig: ConnectionConfig = {
  host: process.env.DB_HOST,
  user: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_DATABASE,
  port: +process.env.DB_PORT,
  ssl: process.env.DB_RDS === "true" ? "Amazon RDS" : undefined
};

const dbConnection: Connection = require("serverless-mysql")({
  config: connectionConfig
});

type HandlerCallback = (error: any, result?: any) => void;

export async function run(event: any, context: any) {
  context.callbackWaitsForEmptyEventLoop = false;

  await partnerSync(dbConnection);
  console.log("DONE");
  await dbConnection.end();
  console.log("CONN ENDED");

  return true;
}
```

**Here is the error:**

```
/Projects/finixPartnerSync/node_modules/serverless-mysql/index.js:56
  const fullJitter = () => randRange(0, Math.min(cap, base * 2 ** retries))
                                                                ^
SyntaxError: Unexpected token *
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Projects/finixPartnerSync/dist/handler.js:54:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at AwsInvokeLocal.invokeLocalNodeJs (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:600:33)
    at AwsInvokeLocal.invokeLocal (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:155:19)
    at AwsInvokeLocal.tryCatcher (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
 
  Error --------------------------------------------------
 
  Error: Exception encountered when loading /Projects/finixPartnerSync/dist/handler
      at AwsInvokeLocal.invokeLocalNodeJs (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:605:13)
      at AwsInvokeLocal.invokeLocal (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:155:19)
  From previous event:
      at Object.AwsInvokeLocal.hooks.invoke:local:invoke [as hook] (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:34:57)
      at BbPromise.reduce (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/lib/classes/PluginManager.js:504:55)
  From previous event:
      at PluginManager.invoke (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/lib/classes/PluginManager.js:504:22)
      at getHooks.reduce.then (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/lib/classes/PluginManager.js:539:24)
  From previous event:
      at PluginManager.run (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/lib/classes/PluginManager.js:539:8)
      at variables.populateService.then (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/lib/Serverless.js:115:33)
      at tryOnImmediate (timers.js:543:15)
      at processImmediate [as _immediateCallback] (timers.js:523:5)
  From previous event:
      at Serverless.run (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/lib/Serverless.js:102:74)
      at serverless.init.then (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/bin/serverless.js:67:28)
      at /Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:136:16
      at /Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:57:14
      at FSReqWrap.oncomplete (fs.js:117:15)
  From previous event:
      at initializeErrorReporter.then (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/bin/serverless.js:67:6)
      at tryOnImmediate (timers.js:543:15)
      at processImmediate [as _immediateCallback] (timers.js:523:5)
  From previous event:
      at Object.<anonymous> (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/bin/serverless.js:53:39)
      at Module._compile (module.js:541:32)
      at Object.Module._extensions..js (module.js:550:10)
      at Module.load (module.js:458:32)
      at tryModuleLoad (module.js:417:12)
      at Function.Module._load (module.js:409:3)
      at Module.runMain (module.js:575:10)
      at run (node.js:348:7)
      at startup (node.js:140:9)
      at node.js:463:3
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              6.2.2
     Framework Version:         1.52.0
     Plugin Version:            2.0.0
     SDK Version:               2.1.1
 
Serverless: 
User stats error: Request network error: %O { FetchError: network timeout at: https://tracking.serverlessteam.com/v1/track
    at Timeout._onTimeout (/Projects/.nvm/versions/node/v6.2.2/lib/node_modules/serverless/node_modules/node-fetch/index.js:126:13)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
  name: 'FetchError',
  message: 'network timeout at: https://tracking.serverlessteam.com/v1/track',
  type: 'request-timeout' }
```

**Comment by lasergoat** [comment]
Solved, closing this issue because it's a node version issue. Somehow I was on node v6, and the `**` and `async` symbols produce syntax errors 🤦🏼‍♂️

**Comment by jeremydaly** [comment]
It happens! Glad you figured it out.
